version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    restart: unless-stopped
  autoapi:
    image: felipevalverde/autoapi:latest
    depends_on:
      - mongo
    ports:
      - 8686:8686
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_ADMIN=admin
      - MONGO_ADMIN_PASS=password
