version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: unless-stopped
  autoapi:
    image: felipevalverde/autoapi:latest
    depends_on:
      - mongo
    ports:
      - 8686:8686
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017